// Regenerates src/data/logo.ts wordmark paths from a font file. One-off dev tool.
// Usage: npm i --no-save opentype.js@1 && node tools/gen-logo.mjs <saira-semi-condensed-latin-600-normal.woff> src/data/logo.ts
// (font: npm pack @fontsource/saira-semi-condensed). Then run `npm run icons`.
import opentype from 'opentype.js';
import fs from 'node:fs';
const [, , fontPath, out] = process.argv;
const font = opentype.loadSync(fontPath);
function line(str, size, tracking) {
  const glyphs = font.stringToGlyphs(str);
  const scale = size / font.unitsPerEm;
  let x = 0; const parts = [];
  glyphs.forEach((g, i) => {
    parts.push(g.getPath(x, 0, size).toPathData(1));
    x += g.advanceWidth * scale + tracking * size;
    if (i < glyphs.length - 1) x += font.getKerningValue(g, glyphs[i + 1]) * scale;
  });
  const width = x - tracking * size;
  const p = new opentype.Path(); // compute bbox
  let minY = Infinity, maxY = -Infinity;
  glyphs.forEach((g) => { const b = g.getPath(0, 0, size).getBoundingBox(); minY = Math.min(minY, b.y1); maxY = Math.max(maxY, b.y2); });
  return { d: parts.join(''), width: +width.toFixed(1), top: +minY.toFixed(1), bottom: +maxY.toFixed(1) };
}
const top = line('ROWE SERVICE’S', 100, 0.075);
const sub = line('SEAMLESS GUTTERS & MORE', 100, 0.06);
fs.writeFileSync(out, `// Official Rowe Service's logo, rebuilt as vector paths (generated by tools/gen-logo.mjs).
// Wordmark: Saira Semi Condensed SemiBold (SIL OFL) outlined to paths, so no font is downloaded.
// Mark: open ring + stylized R, traced from the official 1024px logo.
export const mark = {
  viewBox: '239 104 532 532',
  ring: 'M505 625A255 255 0 1 1 635.2 589.3',
  ringWidth: 22,
  r: 'M345 232H530C605 232 640 282 640 325C640 370 615 400 582 415L672 527L640 597L460 368H535C562 368 580 352 580 328C580 305 562 290 535 290H392Z',
};
export const wordTop = ${JSON.stringify(top)};
export const wordSub = ${JSON.stringify(sub)};
`);
console.log(top.width, top.top, top.bottom, sub.width, sub.top, sub.bottom);
